### ISSUE TITLE
Should setindex(x::AbstractArray, v, i) support arbitrary indices?

### ISSUE THREAD

**Issue by tkf** [JuliaDiffEq/ArrayInterface.jl#17]
https://github.com/JuliaDiffEq/ArrayInterface.jl/blob/c8513cbc0b9dc24e6674206255838abec553b854/src/ArrayInterface.jl#L22-L26

Why not remove type restriction from `Base.setindex` like this?

```julia
function Base.setindex(x::AbstractArray, v, I...)
  _x = copy(x)
  _x[I...] = v
  _x
end
```

**Comment by ChrisRackauckas** [comment]
yeah we should. We should also specialize lower dimensions so it's not assuming mutability, or at least specialize on Tracker.
