### ISSUE TITLE
Julia 1.3

### ISSUE THREAD

**Issue by matthieugomez** [JuliaDiffEq/ArrayInterface.jl#35]
Why does not this package  accept Julia 1.3? 

I'm a bit confused, but it looks like this causes Julia 1.3 to install the latest version of the package in Julia, without respecting any upper bound limit.
For instance, SparseDiffTools has an upper bound for ArrayInterface 2.0 but installing SparseDiffTools on my computer downloaded ArrayInterface 2.3.

**Comment by ChrisRackauckas** [comment]
>For instance, SparseDiffTools has an upper bound for ArrayInterface 2.0 but installing SparseDiffTools on my computer downloaded ArrayInterface 2.3.

SparseDiffTools has an upper bound on ArrayInterface <3.0.0

**Comment by ChrisRackauckas** [comment]
I think this is just a misreading of https://julialang.github.io/Pkg.jl/v1/compatibility/. Feel free to continue discussing though.

**Comment by matthieugomez** [comment]
Oh ok I did not understand that. Thanks!
